# Data Preprocessing Tools

## Importing the libraries

In [83]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [84]:
dataset = pd.read_csv('DATA1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [85]:
print(X)

[['Aws' 2 1630.0 847.6]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Gcp' 4 2461.5 1255.365]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Azure' 8 7210.0 3677.1]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Aws' 2 1630.0 847.6]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Gcp' 4 2461.5 1255.365]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Azure' 8 7210.0 3677.1]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Aws' 2 1630.0 847.6]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Gcp' 4 2461.5 1255.365]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Azure' 8 7

In [86]:
print(y)

['No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes'
 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes']


## Taking care of missing data

In [87]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [88]:
print(X)

[['Aws' 2.0 1630.0 847.6]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Gcp' 4.0 2461.5 1255.365]
 ['Azure' 4.0 2300.0 1196.0]
 ['Aws' 8.0 6520.0 3390.4]
 ['Gcp' 8.0 6352.0 3303.04]
 ['Azure' 8.0 7210.0 3677.1]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Azure' 4.0 2300.0 1196.0]
 ['Aws' 8.0 6520.0 3390.4]
 ['Gcp' 8.0 6352.0 3303.04]
 ['Aws' 2.0 1630.0 847.6]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Gcp' 4.0 2461.5 1255.365]
 ['Azure' 4.0 2300.0 1196.0]
 ['Aws' 8.0 6520.0 3390.4]
 ['Gcp' 8.0 6352.0 3303.04]
 ['Azure' 8.0 7210.0 3677.1]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Azure' 4.0 2300.0 1196.0]
 ['Aws' 8.0 6520.0 3390.4]
 ['Gcp' 8.0 6352.0 3303.04]
 ['Aws' 2.0 1630.0 847.6]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Gcp' 4.0 2461.5 1255.365]
 ['Azure' 4.0 2300.0 

## Encoding categorical data

### Encoding the Independent Variable

In [89]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [90]:
print(X)

[[1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]


### Encoding the Dependent Variable

In [91]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [92]:
print(y)

[0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0
 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0
 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0
 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1]


## Splitting the dataset into the Training set and Test set

In [93]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [94]:
print(X_train)

[[0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [1.0 0.0 0.0 4.0 2267.25 1178.

In [95]:
print(X_test)

[[1.0 0.0 0.0 4.0 2267.25 1178.97]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 0.0 1.0 2.0 1588.0 809.88]]


In [96]:
print(y_train)

[1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 1 1 0 1 1 0 0 0 0
 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 1 1 0 1 1 1 0 1 1 0 1
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 1 1 1 0 0 0
 0 0 1]


In [97]:
print(y_test)

[1 1 1 0 0 0 1 1 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 1 1]


## Feature Scaling

In [98]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 4:] = sc.fit_transform(X_train[:, 4:])
X_test[:, 4:] = sc.transform(X_test[:, 4:])

In [99]:
print(X_train)

[[0.0 0.0 1.0 8.0 1.299751043637937 1.3107253429134482]
 [0.0 1.0 0.0 2.0 -0.7949013093281307 -0.7904092612568646]
 [1.0 0.0 0.0 8.0 1.3771005535397502 1.3883142237796122]
 [0.0 1.0 0.0 4.0 -0.5658454689938921 -0.560644569406171]
 [0.0 0.0 1.0 4.0 -0.49148864846327994 -0.5079194788313104]
 [0.0 1.0 0.0 2.0 -0.7949013093281307 -0.7904092612568646]
 [1.0 0.0 0.0 8.0 1.3771005535397502 1.3883142237796122]
 [1.0 0.0 0.0 4.0 -0.5809240192872516 -0.5757697827893071]
 [0.0 0.0 1.0 4.0 -0.49148864846327994 -0.5079194788313104]
 [1.0 0.0 0.0 8.0 1.3771005535397502 1.3883142237796122]
 [0.0 0.0 1.0 2.0 -0.8936600585777673 -0.9035774755421966]
 [1.0 0.0 0.0 8.0 1.3771005535397502 1.3883142237796122]
 [1.0 0.0 0.0 4.0 -0.5809240192872516 -0.5757697827893071]
 [0.0 1.0 0.0 4.0 -0.5658454689938921 -0.560644569406171]
 [1.0 0.0 0.0 8.0 1.3771005535397502 1.3883142237796122]
 [1.0 0.0 0.0 4.0 -0.5809240192872516 -0.5757697827893071]
 [1.0 0.0 0.0 2.0 -0.874322681102314 -0.8700764157176579]
 [0.0 1.0 0

In [100]:
print(X_test)

[[1.0 0.0 0.0 4.0 -0.5809240192872516 -0.5757697827893071]
 [1.0 0.0 0.0 4.0 -0.5809240192872516 -0.5757697827893071]
 [0.0 0.0 1.0 2.0 -0.8936600585777673 -0.9035774755421966]
 [0.0 1.0 0.0 4.0 -0.5658454689938921 -0.560644569406171]
 [0.0 1.0 0.0 4.0 -0.5658454689938921 -0.560644569406171]
 [1.0 0.0 0.0 2.0 -0.874322681102314 -0.8700764157176579]
 [0.0 0.0 1.0 8.0 1.299751043637937 1.3107253429134482]
 [0.0 0.0 1.0 8.0 1.299751043637937 1.3107253429134482]
 [1.0 0.0 0.0 8.0 1.3771005535397502 1.3883142237796122]
 [0.0 0.0 1.0 8.0 1.299751043637937 1.3107253429134482]
 [0.0 1.0 0.0 2.0 -0.7949013093281307 -0.7904092612568646]
 [0.0 1.0 0.0 8.0 1.6947860406364832 1.6429471466771532]
 [0.0 1.0 0.0 2.0 -0.7949013093281307 -0.7904092612568646]
 [1.0 0.0 0.0 4.0 -0.5809240192872516 -0.5757697827893071]
 [0.0 0.0 1.0 8.0 1.299751043637937 1.3107253429134482]
 [0.0 0.0 1.0 2.0 -0.8936600585777673 -0.9035774755421966]
 [0.0 1.0 0.0 4.0 -0.5658454689938921 -0.560644569406171]
 [1.0 0.0 0.0 2.0

Multiple Linear Regression


In [101]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [103]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 0.46  1.  ]
 [ 0.46  1.  ]
 [ 0.76  1.  ]
 [ 0.12  0.  ]
 [ 0.12  0.  ]
 [ 0.36  0.  ]
 [ 0.73  1.  ]
 [ 0.73  1.  ]
 [ 0.28  0.  ]
 [ 0.73  1.  ]
 [-0.    0.  ]
 [-0.29  0.  ]
 [-0.    0.  ]
 [ 0.46  1.  ]
 [ 0.73  1.  ]
 [ 0.76  1.  ]
 [ 0.12  0.  ]
 [ 0.36  0.  ]
 [-0.29  0.  ]
 [ 0.82  0.  ]
 [-0.    0.  ]
 [-0.    0.  ]
 [-0.    0.  ]
 [-0.29  0.  ]
 [ 0.73  1.  ]
 [ 0.12  0.  ]
 [ 0.46  1.  ]
 [ 0.76  1.  ]
 [ 0.76  1.  ]]
