# Data Preprocessing Tools

## Importing the libraries

In [66]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [67]:
dataset = pd.read_csv('DATA1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [68]:
print(X)

[['Aws' 2 1630.0 847.6]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Gcp' 4 2461.5 1255.365]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Azure' 8 7210.0 3677.1]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Aws' 2 1630.0 847.6]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Gcp' 4 2461.5 1255.365]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Azure' 8 7210.0 3677.1]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Aws' 2 1630.0 847.6]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Gcp' 4 2461.5 1255.365]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Azure' 8 7

In [69]:
print(y)

['No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes'
 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes']


## Taking care of missing data

In [70]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [71]:
print(X)

[['Aws' 2.0 1630.0 847.6]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Gcp' 4.0 2461.5 1255.365]
 ['Azure' 4.0 2300.0 1196.0]
 ['Aws' 8.0 6520.0 3390.4]
 ['Gcp' 8.0 6352.0 3303.04]
 ['Azure' 8.0 7210.0 3677.1]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Azure' 4.0 2300.0 1196.0]
 ['Aws' 8.0 6520.0 3390.4]
 ['Gcp' 8.0 6352.0 3303.04]
 ['Aws' 2.0 1630.0 847.6]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Gcp' 4.0 2461.5 1255.365]
 ['Azure' 4.0 2300.0 1196.0]
 ['Aws' 8.0 6520.0 3390.4]
 ['Gcp' 8.0 6352.0 3303.04]
 ['Azure' 8.0 7210.0 3677.1]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Azure' 4.0 2300.0 1196.0]
 ['Aws' 8.0 6520.0 3390.4]
 ['Gcp' 8.0 6352.0 3303.04]
 ['Aws' 2.0 1630.0 847.6]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Gcp' 4.0 2461.5 1255.365]
 ['Azure' 4.0 2300.0 

## Encoding categorical data

### Encoding the Independent Variable

In [72]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [73]:
print(X)

[[1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]


### Encoding the Dependent Variable

In [74]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [75]:
print(y)

[0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0
 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0
 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0
 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1]


## Splitting the dataset into the Training set and Test set

In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [77]:
print(X_train)

[[0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [

In [78]:
print(X_test)

[[1.0 0.0 0.0 2.0 1630.0 847.6]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [1.0 0.0 0.0 8.0 6520.0

In [79]:
print(y_train)

[1 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1 1 0 0 0 0 1 1 1 0 0 0 0 1 0
 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 0
 1 0 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0]


In [80]:
print(y_test)

[0 0 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 0 1 1 1 1 0 1 0 1 0 1 1 0 0 0 0 0 0 0]


## Feature Scaling

In [81]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [82]:
print(X_train)

[[-0.66779184 -0.74210824  1.4043583  -1.04787366 -0.87613045 -0.88632567]
 [-0.66779184  1.34751233 -0.71206899 -0.24699879 -0.54994482 -0.54462947]
 [ 1.49747262 -0.74210824 -0.71206899  1.35475095  1.38334647  1.39730089]
 [-0.66779184  1.34751233 -0.71206899 -1.04787366 -0.77786245 -0.77356557]
 [-0.66779184  1.34751233 -0.71206899 -0.24699879 -0.54994482 -0.54462947]
 [ 1.49747262 -0.74210824 -0.71206899 -0.24699879 -0.56494844 -0.55970014]
 [ 1.49747262 -0.74210824 -0.71206899 -1.04787366 -0.85688917 -0.85294543]
 [ 1.49747262 -0.74210824 -0.71206899  1.35475095  1.38334647  1.39730089]
 [ 1.49747262 -0.74210824 -0.71206899 -1.04787366 -0.85688917 -0.85294543]
 [-0.66779184  1.34751233 -0.71206899 -0.24699879 -0.54994482 -0.54462947]
 [-0.66779184  1.34751233 -0.71206899  1.35475095  1.69945334  1.65101555]
 [ 1.49747262 -0.74210824 -0.71206899  1.35475095  1.38334647  1.39730089]
 [-0.66779184 -0.74210824  1.4043583   1.35475095  1.30638132  1.31999182]
 [ 1.49747262 -0.74210824

In [83]:
print(X_test)

[[ 1.49747262 -0.74210824 -0.71206899 -1.04787366 -0.85688917 -0.85294543]
 [ 1.49747262 -0.74210824 -0.71206899  1.35475095  1.38334647  1.39730089]
 [-0.66779184 -0.74210824  1.4043583  -1.04787366 -0.87613045 -0.88632567]
 [ 1.49747262 -0.74210824 -0.71206899 -0.24699879 -0.56494844 -0.55970014]
 [-0.66779184 -0.74210824  1.4043583   1.35475095  1.30638132  1.31999182]
 [-0.66779184 -0.74210824  1.4043583   1.35475095  1.30638132  1.31999182]
 [ 1.49747262 -0.74210824 -0.71206899 -0.24699879 -0.56494844 -0.55970014]
 [-0.66779184 -0.74210824  1.4043583   1.35475095  1.30638132  1.31999182]
 [-0.66779184  1.34751233 -0.71206899 -1.04787366 -0.77786245 -0.77356557]
 [ 1.49747262 -0.74210824 -0.71206899 -0.24699879 -0.56494844 -0.55970014]
 [-0.66779184 -0.74210824  1.4043583  -0.24699879 -0.47595748 -0.49209452]
 [-0.66779184 -0.74210824  1.4043583   1.35475095  1.30638132  1.31999182]
 [-0.66779184  1.34751233 -0.71206899  1.35475095  1.69945334  1.65101555]
 [ 1.49747262 -0.74210824

 KNN

 KNN


In [84]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [85]:
print(classifier.predict(sc.transform([[0.0, 0.0, 1.0, 2.0, 1588.0, 809.88]])))


[1]


In [86]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]]


In [87]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[16  2]
 [ 8 10]]


0.7222222222222222