# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('DATA1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[['Aws' 2 1630.0 847.6]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Gcp' 4 2461.5 1255.365]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Azure' 8 7210.0 3677.1]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Aws' 2 1630.0 847.6]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Gcp' 4 2461.5 1255.365]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Azure' 8 7210.0 3677.1]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Aws' 2 1630.0 847.6]
 ['Gcp' 2 1588.0 809.88]
 ['Azure' 2 1802.5 937.3]
 ['Aws' 4 2267.25 1178.97]
 ['Gcp' 4 2461.5 1255.365]
 ['Azure' 4 2300.0 1196.0]
 ['Aws' 8 6520.0 3390.4]
 ['Gcp' 8 6352.0 3303.04]
 ['Azure' 8 7

In [ ]:
print(y)

['No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes'
 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes']


## Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
print(X)

[['Aws' 2.0 1630.0 847.6]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Gcp' 4.0 2461.5 1255.365]
 ['Azure' 4.0 2300.0 1196.0]
 ['Aws' 8.0 6520.0 3390.4]
 ['Gcp' 8.0 6352.0 3303.04]
 ['Azure' 8.0 7210.0 3677.1]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Azure' 4.0 2300.0 1196.0]
 ['Aws' 8.0 6520.0 3390.4]
 ['Gcp' 8.0 6352.0 3303.04]
 ['Aws' 2.0 1630.0 847.6]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Gcp' 4.0 2461.5 1255.365]
 ['Azure' 4.0 2300.0 1196.0]
 ['Aws' 8.0 6520.0 3390.4]
 ['Gcp' 8.0 6352.0 3303.04]
 ['Azure' 8.0 7210.0 3677.1]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Azure' 4.0 2300.0 1196.0]
 ['Aws' 8.0 6520.0 3390.4]
 ['Gcp' 8.0 6352.0 3303.04]
 ['Aws' 2.0 1630.0 847.6]
 ['Gcp' 2.0 1588.0 809.88]
 ['Azure' 2.0 1802.5 937.3]
 ['Aws' 4.0 2267.25 1178.97]
 ['Gcp' 4.0 2461.5 1255.365]
 ['Azure' 4.0 2300.0 

## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0
 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0
 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0
 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

[[0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [1.0 0.0 0.0 4.0 2267.25 1178.

In [ ]:
print(X_test)

[[1.0 0.0 0.0 4.0 2267.25 1178.97]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [1.0 0.0 0.0 8.0 6520.0 3390.4]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 2.0 1630.0 847.6]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 0.0 1.0 4.0 2461.5 1255.365]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [0.0 1.0 0.0 2.0 1802.5 937.3]
 [0.0 1.0 0.0 8.0 7210.0 3677.1]
 [0.0 0.0 1.0 8.0 6352.0 3303.04]
 [0.0 1.0 0.0 4.0 2300.0 1196.0]
 [1.0 0.0 0.0 4.0 2267.25 1178.97]
 [0.0 0.0 1.0 2.0 1588.0 809.88]
 [0.0 0.0 1.0 2.0 1588.0 809.88]]


In [ ]:
print(y_train)

[1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 1 1 0 1 1 0 0 0 0
 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 1 1 0 1 1 1 0 1 1 0 1
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 1 1 1 0 0 0
 0 0 1]


In [ ]:
print(y_test)

[1 1 1 0 0 0 1 1 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 1 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 4:] = sc.fit_transform(X_train[:, 4:])
X_test[:, 4:] = sc.transform(X_test[:, 4:])

In [ ]:
print(X_train)

[[0.0 0.0 1.0 8.0 1.299751043637937 1.3107253429134482]
 [0.0 1.0 0.0 2.0 -0.7949013093281307 -0.7904092612568646]
 [1.0 0.0 0.0 8.0 1.3771005535397502 1.3883142237796122]
 [0.0 1.0 0.0 4.0 -0.5658454689938921 -0.560644569406171]
 [0.0 0.0 1.0 4.0 -0.49148864846327994 -0.5079194788313104]
 [0.0 1.0 0.0 2.0 -0.7949013093281307 -0.7904092612568646]
 [1.0 0.0 0.0 8.0 1.3771005535397502 1.3883142237796122]
 [1.0 0.0 0.0 4.0 -0.5809240192872516 -0.5757697827893071]
 [0.0 0.0 1.0 4.0 -0.49148864846327994 -0.5079194788313104]
 [1.0 0.0 0.0 8.0 1.3771005535397502 1.3883142237796122]
 [0.0 0.0 1.0 2.0 -0.8936600585777673 -0.9035774755421966]
 [1.0 0.0 0.0 8.0 1.3771005535397502 1.3883142237796122]
 [1.0 0.0 0.0 4.0 -0.5809240192872516 -0.5757697827893071]
 [0.0 1.0 0.0 4.0 -0.5658454689938921 -0.560644569406171]
 [1.0 0.0 0.0 8.0 1.3771005535397502 1.3883142237796122]
 [1.0 0.0 0.0 4.0 -0.5809240192872516 -0.5757697827893071]
 [1.0 0.0 0.0 2.0 -0.874322681102314 -0.8700764157176579]
 [0.0 1.0 0

In [ ]:
print(X_test)

[[1.0 0.0 0.0 4.0 -0.5809240192872516 -0.5757697827893071]
 [1.0 0.0 0.0 4.0 -0.5809240192872516 -0.5757697827893071]
 [0.0 0.0 1.0 2.0 -0.8936600585777673 -0.9035774755421966]
 [0.0 1.0 0.0 4.0 -0.5658454689938921 -0.560644569406171]
 [0.0 1.0 0.0 4.0 -0.5658454689938921 -0.560644569406171]
 [1.0 0.0 0.0 2.0 -0.874322681102314 -0.8700764157176579]
 [0.0 0.0 1.0 8.0 1.299751043637937 1.3107253429134482]
 [0.0 0.0 1.0 8.0 1.299751043637937 1.3107253429134482]
 [1.0 0.0 0.0 8.0 1.3771005535397502 1.3883142237796122]
 [0.0 0.0 1.0 8.0 1.299751043637937 1.3107253429134482]
 [0.0 1.0 0.0 2.0 -0.7949013093281307 -0.7904092612568646]
 [0.0 1.0 0.0 8.0 1.6947860406364832 1.6429471466771532]
 [0.0 1.0 0.0 2.0 -0.7949013093281307 -0.7904092612568646]
 [1.0 0.0 0.0 4.0 -0.5809240192872516 -0.5757697827893071]
 [0.0 0.0 1.0 8.0 1.299751043637937 1.3107253429134482]
 [0.0 0.0 1.0 2.0 -0.8936600585777673 -0.9035774755421966]
 [0.0 1.0 0.0 4.0 -0.5658454689938921 -0.560644569406171]
 [1.0 0.0 0.0 2.0

Multiple Linear Regression


In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[15  1]
 [ 4  9]]


0.8275862068965517